version: "3.9"

services:
  api:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0.29
    container_name: go_playground_db
    environment:
      MYSQL_DATABASE: go_playground
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db_data:/var/lib/mysql

volumes:
  db_data:
