version: "3.9"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0.29
    container_name: go_playground_db
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db_data:/var/lib/mysql
    env_file:
      - .env

volumes:
  db_data:
