version: "3.9"

services:
  api:
    container_name: go_playground_api
    build: .
    command: "air -c .air.toml -- -h"
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env

  db:
    container_name: go_playground_db
    image: mysql:8.0.29
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql
    env_file:
      - .env
